# Generated by Django 2.1.7 on 2019-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prezzee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
